Import('env')

if env['default_instrumentation']:
  env.SConscript('llvm/SConscript')
  env.SConscript('lib/SConscript')

  if env['default_instrumentation_examples']:
	env.SConscript('examples/SConscript')
