Import('env')

env.SConscript('llvm/SConscript')
env.SConscript('lib/SConscript')

if env['default_instrumentation_examples']:
  env.SConscript('examples/SConscript')

env.SConscript('obs2cspectra/SConscript')
env.SConscript('obs2gviz/SConscript')
env.SConscript('proxy/SConscript')
