Import('env')
env = env.Clone()
env.Append(
	CPPPATH = Dir(env['common_dir']),
	LINKFLAGS = "-lpthread -lboost_system -lboost_thread -lmpfr -L%s -ldiag" % env['lib_dir'] )

sources = Glob('*.cpp')

obj = env.Program(target = "diagnosis.test", source = sources)
env.Depends(obj, env['libdiag_shared'])
env.Default(env.Install(env['bin_dir'], obj))
