import os
import SCons
from os.path import join
from SCons.Scanner.C import CScanner

Import('env')
env = env.Clone()
env.Tool('RecursiveScanner')
env.Append(
	CPPPATH = [env['common_include_dir'], " -Wno-c++11-extensions"], 
	LINKFLAGS = "-lpthread -lboost_system -lboost_thread")

target  = "sandbox"

wildcards = ""
headers = []
common_headers = []
sources = []

for i in range(4):
  wildcards = join(wildcards, "*")
  headers += env.Glob(wildcards + "h")
  sources += env.Glob(wildcards + "cpp")
  sources += env.Glob(join("..", "common", "src", wildcards + "cpp"))

obj = env.Program(target = target, source = sources)
env.Default(env.Install(env['bin_dir'], obj))
