Import('env')
env = env.Clone()

target  = "llvminstrument"
sources = Glob("*cpp") + Glob("*/*cpp")

env.Append(
		CCFLAGS = "-O0 -g -I%s `llvm-config --cxxflags`" % env['common_include_dir'],
		LINKFLAGS = "-g -lpthread `llvm-config --ldflags`")


obj = env.SharedLibrary(target = target, source = sources)
lib_install = env.Install(env['lib_dir'], obj)

env.Default(lib_install)
