Import('env')
env = env.Clone()

target  = "llvminstrument"
sources = Glob("*cpp") + Glob("*/*cpp")

llvm_ccflags = "`%s --cxxflags`" % env['llvmconfig']
llvm_ldflags = "`%s --ldflags --libs`" % env['llvmconfig']

env.Append(
	CCFLAGS = " -I%s %s" % (env['common_include_dir'], llvm_ccflags),
	LINKFLAGS = llvm_ldflags)


obj = env.SharedLibrary(target = target, source = sources)
lib_install = env.Install(env['lib_dir'], obj)

env.Default(lib_install)
