Import('env')
env = env.Clone()
env.Append(
	CCFLAGS = " -Wno-c++11-extensions " + env['mpi_include'],
	CPPPATH = Dir(env['common_dir']),
	LINKFLAGS = "-lpthread -lboost_system -lboost_thread  -L%s -l%s %s " % (env['lib_dir'], env['libdiag'], env['mpi_link']) )

sources = Glob("*cpp")

obj = env.Program(target = "barinel", source = sources)
env.Depends(obj, env['libdiag_shared'])
env.Default(env.Install(env['bin_dir'], obj))
