Import('env')
env = env.Clone()
env.Append(
	CCFLAGS = " -Wno-c++11-extensions " + '`mpic++ --showme:compile`',
	CPPPATH = Dir(env['common_dir']),
	LINKFLAGS = "-lpthread -lboost_system -lboost_thread " + '`mpic++ --showme:link`')


sources = env['common_objects'] + [ Glob("*cpp")]




obj = env.Program(target = "barinel", source = sources)
env.Default(env.Install(env['bin_dir'], obj))
