import os

Import('env')
env = env.Clone()

target = "fractal"
sources = Glob("*.cpp")

obj = env.Instrument(target, sources, env['llvm_passes'])
env.Depends(obj, env['libinstrument_shared'])

bin_install = env.Install(env['bin_dir'], obj)
env.Default(bin_install)
