import os

Import('env')
env = env.Clone()

target = "webfsd"
sources = Glob("*.c")


defines = "\
		-Wno-pointer-sign\
		-DMIMEFILE=\\\"/etc/mime.types\\\"\
        -DWEBFS_VERSION=\\\"libinstrument_example\\\"\
        -D_GNU_SOURCE \
        -D_LARGEFILE_SOURCE \
        -D_LARGEFILE64_SOURCE \
        -D_FILE_OFFSET_BITS=64\
        -UUSE_SSL\
        -DUSE_THREADS=1\
        -D_REENTRANT"

env.Append(LINKFLAGS = " -lpthread", CFLAGS = defines)


obj = env.Instrument(target, sources, env['llvm_passes'])

bin_install = env.Install(env['bin_dir'], obj)

env.Default(bin_install)
