from os.path import join

Import('env')
env = env.Clone()

env.Append(LINKFLAGS = "-lpthread -lboost_system -lboost_thread -Wl,-rpath,'$$ORIGIN'")


target  = "instrument"



wildcards = ""
sources = []
common_sources = []

for i in range(4):
  wildcards = join(wildcards, "*")
  sources += env.Glob(wildcards + "cpp")

obj = env.SharedLibrary(target = target, source = sources)

lib_install = env.Install(env['lib_dir'], obj)
env.Default(lib_install)


headers = Glob("interface/*.h")
header_install_dir = join(env['include_dir'], "lib%s" % env['libinstrument'])

for h in headers:
  install = env.Install(header_install_dir, h)
  env.Default(install)
