Import('env')
env = env.Clone()
env.Append(LINKFLAGS = " -L%s -ldiag" % env['lib_dir'] )

sources = Glob('*.cpp')

obj = env.Program(target = "sandox", source = sources)
env.Default(env.Install(env['bin_dir'], obj))
