import os
Import("build_info")

def buildWebfs(target, passes):
    sources = Glob("*.c")
	
    llvm_instrument_lib = build_info['build_dir'] + "/llvminstrument/libllvminstrument.so"
    instrument_lib = build_info['build_dir'] + "/libinstrument/libinstrument.so"
    link_path = build_info['build_dir'] + "/libinstrument"

    defines = " -DMIMEFILE=\\\"/etc/mime.types\\\"\
            -DWEBFS_VERSION=\\\"luskfusk\\\"\
            -D_GNU_SOURCE \
            -D_LARGEFILE_SOURCE \
            -D_LARGEFILE64_SOURCE \
            -D_FILE_OFFSET_BITS=64\
            -UUSE_SSL\
            -DUSE_THREADS=1\
            -D_REENTRANT"

    env = Environment(
        tools=['Instrument'],
        LLVM_INSTRUMENT_LIB = llvm_instrument_lib,
        INSTRUMENT_LIB = instrument_lib,
        CFLAGS = defines,
        LINK_PATH = "-L"+link_path,
        LINKFLAGS = "-L" + link_path + " -lpthread -linstrument")
    env.Append(CPP_PATH = "-I"+build_info['common_include_dir'])
    env['ENV']['TERM'] = os.environ['TERM']
    env["CXX"] = "clang++"

    obj = env.Instrument(target, sources, passes)
    bin_install = env.Install(build_info['build_dir'] + "/bin", obj)
    env.Default(bin_install)
	
buildWebfs('webfsd', "-instrument_prepare")
#buildWebfs('webfsd_function', "-instrument_function -instrument_prepare")
#buildWebfs('webfsd_block', "-instrument_block -instrument_prepare")


