import os
Import("build_info")
env = env.Clone()

target = "webfsd"
sources = Glob("*.c")

defines = " -DMIMEFILE=\\\"/etc/mime.types\\\"\
        -DWEBFS_VERSION=\\\"libinstrument_example\\\"\
        -D_GNU_SOURCE \
        -D_LARGEFILE_SOURCE \
        -D_LARGEFILE64_SOURCE \
        -D_FILE_OFFSET_BITS=64\
        -UUSE_SSL\
        -DUSE_THREADS=1\
        -D_REENTRANT"

env = Environment(
    tools=['Instrument'],
    LLVM_INSTRUMENT_LIB = build_info['llvm_optimizer'],
    INSTRUMENT_LIB = build_info['lib_instrument'],
    LINK_PATH = "-L%s" % build_info['lib_dir'],
    LINKFLAGS = "-lpthread -linstrument",
    CFLAGS = defines)
env.Append(CPP_PATH = "-I"+build_info['include_dir'])
env['ENV']['TERM'] = os.environ['TERM']
env["CXX"] = "clang++"

obj = env.Instrument(target, sources, build_info['llvm_passes'])

bin_install = env.Install(build_info['bin_dir'], obj)

env.Default(bin_install)
