from os.path import join
import os

Import('env')
env = env.Clone()

target  = "fractal"
sources = Glob("*.cpp")

env.Append(
    LLVM_INSTRUMENT_LIB = join(env['lib_dir'], "lib%s.%s" % (env['llvminstrument'], env['libext'])),
    INSTRUMENT_LIB = join(env['lib_dir'], "lib%s.%s" % (env['libinstrument'], env['libext'])),
    LINK_PATH = "-L%s" % env['lib_dir'],
    LINKFLAGS = "-lpthread -l%s" % env['libinstrument'],
	CPP_PATH = "-I%s" % env['include_dir'])
env.Tool('Instrument')

obj = env.Instrument(target, sources, env['llvm_passes'])
bin_install = env.Install(env['bin_dir'], obj)

env.Default(bin_install)
