Import('env')
env = env.Clone()
env.Append(
	CCFLAGS = " -Wno-c++11-extensions ",
	CPPPATH = Dir(env['common_dir']),
	LINKFLAGS = "-L%s -l%s -lboost_thread -lboost_system " % (env['lib_dir'], env['libdiag']) )

sources = Glob("*cpp")

obj = env.Program(target = "cmeans", source = sources)
env.Depends(obj, env['libdiag_shared'])
env.Default(env.Install(env['bin_dir'], obj))
