import os

Import('env')
env = env.Clone()

target = "fractal"
sources = Glob("*.cpp")

env.Append(LINKFLAGS = " -lpthread")

obj = env.Instrument(target, sources, env['llvm_passes'])
bin_install = env.Install(env['bin_dir'], obj)

env.Default(bin_install)
