import os

def getSubdirs(abs_path_dir) :
    lst = [ name for name in os.listdir(abs_path_dir) if os.path.isdir(os.path.join(abs_path_dir, name)) and name[0] != '.' ]
    lst.sort()
    return lst



Import("env")
instr_env = env

env.Tool('Instrument')

sub_folders = getSubdirs(Dir('#').abspath)
for f in sub_folders:
    if f == instr_env['build_dir'].name:
        continue
    f = File(os.path.join(f, "SConscript"))
    if f.exists():
        env = instr_env.Clone()
        env.SConscript(f)
