/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_crowbar_diagnostic_algorithms_DiagnosticJob_Connection */

#ifndef _Included_io_crowbar_diagnostic_algorithms_DiagnosticJob_Connection
#define _Included_io_crowbar_diagnostic_algorithms_DiagnosticJob_Connection
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
