/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_crowbar_diagnosis_algorithms_DiagnosticJob */

#ifndef _Included_io_crowbar_diagnosis_algorithms_DiagnosticJob
#define _Included_io_crowbar_diagnosis_algorithms_DiagnosticJob
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_crowbar_diagnosis_algorithms_DiagnosticJob
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_crowbar_diagnosis_algorithms_DiagnosticJob_run
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
