Import('env')
env = env.Clone()
env.Append(
	CCFLAGS = " -Wno-c++11-extensions ",
	CPPPATH = Dir(env['common_dir']),
	LINKFLAGS = "-l%s" % (env['libdiag']) )

sources = Glob("*cpp")

obj = env.Program(target = "cmeans", source = sources)
env.Default(env.Install(env['bin_dir'], obj))
