#!/bin/bash
  echo "--------------------------"

[[ -z $CLANG ]] && CLANG=clang
[[ -z $OPT ]] && OPT=opt
[[ -z $LLC ]] && LLC=llc


SOURCE=""
TARGET=""
CLANG_OPTS=""


CLANG_ARGS=`$CLANG -'###' $@ 2>&1 | grep '"-o"'`
eval CLANG_ARGS=($CLANG_ARGS)

I=0
while ((${#CLANG_ARGS[@]} > I)); do
  opt=${CLANG_ARGS[$I]}
  if [[ $opt  == "-o" ]]; then
	I=$((I+1))
	TARGET="-o ${CLANG_ARGS[$I]}"
  fi
  I=$((I+1))
done

while [[ -n $@ ]]; do
  [[ $1  == "-o" ]] && shift 2 && continue
  [[ $1  == "-c" ]] && COMPILE=1
  CLANG_OPTS="$CLANG_OPTS $1"
  shift
done

[[ -z $LLVM_INSTRUMENT_LIB ]] && LLVM_INSTRUMENT_LIB=/usr/lib/libllvminstrument.so
[[ -z $LLVM_PASSES ]] && LLVM_PASSES="-instrument_block -instrument_prepare"


if [[ $COMPILE ]]; then
  [[ -z $TMPDIR ]] && TMPDIR=`mktemp -d`
  TMP_CREATOR="mktemp -p $TMPDIR --suffix"
  [[ -z $LLVM_OUT ]] && LLVM_OUT=`$TMP_CREATOR .llvm`
  [[ -z $OPT_OUT ]] && OPT_OUT=`$TMP_CREATOR .llvmi`
  [[ -z $LLC_OUT ]] && LLC_OUT=`$TMP_CREATOR .s`

  echo "clang"
  $CLANG -S -emit-llvm -g $CLANG_OPTS -c -o $LLVM_OUT || exit 1

  echo "opt"
  $OPT -S -f --load $LLVM_INSTRUMENT_LIB $LLVM_PASSES $LLVM_OUT -o $OPT_OUT || exit 1

  echo "llc"
  $LLC -o $LLC_OUT < $OPT_OUT || exit 1
  
  echo "clang"
  $CLANG -c $LLC_OUT $TARGET || exit 1

  rm $TMPDIR -r
else
  $CLANG $CLANG_OPTS $TARGET
fi
