import os
from os.path import join

Import('env')
oldenv = env
env = oldenv.Clone()
env.Append(CPPPATH = Dir(env['common_dir']), 
	LINKFLAGS = " -lboost_system -lboost_thread %s" % env['mpfr_link']  )

header_install_dir = join(env['include_dir'], "lib%s" % env['libdiag'])

wildcards = ""
headers = []
sources = []

for i in range(4):
  wildcards = join(wildcards, "*")
  headers += env.Glob(wildcards + "h")
  sources += env.Glob(wildcards + "cpp")

common_objects = env.SharedObject(sources)
oldenv['common_objects'] = common_objects

env.Default(common_objects)

libdiag = env.SharedLibrary(target = 'libdiag', source=common_objects)
libdiag = env.Install(env['lib_dir'], libdiag)
env.Default(libdiag)
oldenv['libdiag_shared'] = libdiag

libdiagstatic = env.StaticLibrary(target = 'libdiag', source=common_objects)
libdiagstatic = env.Install(env['lib_dir'], libdiagstatic)
oldenv['libdiag_static'] = libdiagstatic

for h in headers:
  install = join(header_install_dir, os.path.dirname(str(h)))
  install = env.Install(install, h)
  env.Default(install)
