Import('env')
env = env.Clone()
env.Append(
	CCFLAGS= " -Wno-c++11-extensions",
	CPPPATH = Dir(env['common_dir']),
	LINKFLAGS = "-lpthread -lboost_system -lboost_thread -L%s -ldiag" % env['lib_dir'] )

sources = Glob("*cpp")

obj = env.Program(target = "proxy", source = sources)
env.Default(env.Install(env['bin_dir'], obj))
