from os.path import join

Import('env')
env = env.Clone()
env.Append(
	CCFLAGS= " -Wno-c++11-extensions `Rscript -e 'Rcpp:::CxxFlags()'`",
	CPPPATH = [Dir(env['common_dir']), Dir(env['R_include'])],
	LINKFLAGS = " ".join([" -lboost_system",
                              "-lboost_thread",
                              "-lboost_date_time",
                              "-lboost_filesystem",
                              "`Rscript -e 'Rcpp:::LdFlags()'`",
                              join(env['lib_dir'], "lib" + env['libdiag'] + ".a"),
                              env['mpfr_link']]))

sources = [Glob("src/*cpp")] + env['common_objects']

obj = env.SharedLibrary(target = "libRdiag", source = sources)
path = "*"
for i in range(3):
	env.Depends(obj, Dir('pkg').srcnode().glob(path, source=True))
	path = join(path, '*')


env.Depends(obj, env['libdiag_static'])

env.Default(obj)

Alias("install_libRdiag",
      env.Command(".phony",
                  obj,
                  "\n".join(["R CMD INSTALL tools/libRdiag/pkg libRdiag --no-test-load",
                            "mkdir ~/.R/libRdiag/libs",
                            "cp %s ~/.R/libRdiag/libs" % obj[0].get_abspath()])))
