from os.path import join

Import('env')
env = env.Clone()

llvm_ccflags = " `%s --cxxflags`" % env['llvmconfig']
llvm_ldflags = " `%s --ldflags --libs`" % env['llvmconfig']

env.Append(CPPPATH = Dir(env['common_dir']),
	CCFLAGS = llvm_ccflags,
	LINKFLAGS = llvm_ldflags)

target  = "llvm_spectra_instrument"

sources = []
wildcards = ""
for i in range(4):
  wildcards = join(wildcards, "*")
  sources += env.Glob(wildcards + "cpp")

print [str(x) for x in sources]
obj = env.SharedLibrary(target = target, source = sources)
lib_install = env.Install(env['lib_dir'], obj)
env.Default(lib_install)
