Import('env')
oldenv = env
env = env.Clone()

	
env.Append(LINKFLAGS = " -Wl,-rpath,'$$ORIGIN/../lib' ")
Export('env')

env.SConscript('barinel/SConscript')
env.SConscript('iscandidate/SConscript')
env.SConscript('knn/SConscript')
env.SConscript('mhs/SConscript')
env.SConscript('obs2cspectra/SConscript')
env.SConscript('obs2gviz/SConscript')
env.SConscript('proxy/SConscript')
env.SConscript('trie/SConscript')

env = oldenv
Export('env')
